[package]
name = "rustimagequant"
version = "0.1.0"
authors = ["DarthSim <darthsim@gmail.com>"]
edition = "2018"

[lib]
name = "imagequant"
crate-type = ["cdylib"]

[profile.release]
lto = true

[dependencies]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
