header = "// SPDX-License-Identifier: MIT"
# sys_includes = ["stddef.h", "stdint.h", "stdlib.h"]
# no_includes = true
include_guard = "QUANTIZR_H"
tab_width = 2
style = "Type"
language = "C"

[export.rename]
"Options" = "QuantizrOptions"
"QuantizeResult" = "QuantizrResult"
"Histogram" = "QuantizrHistogram"
"Image" = "QuantizrImage"
"Error" = "QuantizrError"
"Color" = "QuantizrColor"
"Palette" = "QuantizrPalette"

[enum]
rename_variants = "ScreamingSnakeCase"
